http_endpoint = "http://anvil:8545"
ws_endpoint = "ws://anvil:8545"
registry_coordinator_address = "0x1613beB3B2C4f22Ee086B2b38C1476A3cE7f78E8"
operator_state_retriever_address = "0x95401dc811bb5740090279Ba06cfA8fcF6113778"
current_first_block = 1
task_issuer = "0xB819BA4c5d2b64d07575ff4B30d3e0Eca219BFd5"
callback_address = "0xB819BA4c5d2b64d07575ff4B30d3e0Eca219BFd5"
ruleset = "B819BA4c5d2b64d07575ff4B30d3e0Eca219BFd5"
socket = "http://operator:3033"
secret_key = ""
payment_phrase = ""
postgre_connect_request = "host=postgres dbname=db user=user password=password"
payment_token = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
max_ops = 1